-- ISSUE STATUSES
INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 1, 'TO_DO'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=1 AND STATUS_NAME='TO_DO');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 2, 'IN_PROGRESS'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=2 AND STATUS_NAME='IN_PROGRESS');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 3, 'CODE_REVIEW'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=3 AND STATUS_NAME='CODE_REVIEW');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 4, 'IN_TESTS'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=4 AND STATUS_NAME='IN_TESTS');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 5, 'DONE'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=5 AND STATUS_NAME='DONE');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 6, 'TEST'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=6 AND STATUS_NAME='TEST');

-- ISSUE TYPES

INSERT INTO ISSUE_TYPE(ISSUE_TYPEID, TYPE)
SELECT 1, 'USER_STORY'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_TYPE WHERE ISSUE_TYPEID=1 AND TYPE='USER_STORY');

INSERT INTO ISSUE_TYPE(ISSUE_TYPEID, TYPE)
SELECT 2, 'BUG'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_TYPE WHERE ISSUE_TYPEID=2 AND TYPE='BUG');

INSERT INTO ISSUE_TYPE(ISSUE_TYPEID, TYPE)
SELECT 3, 'TO_DO'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_TYPE WHERE ISSUE_TYPEID=3 AND TYPE='TO_DO');

-- ISSUE PRIORITIES

INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY)
SELECT 1, 'CRITICAL'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_PRIORITY WHERE ISSUE_PRIORITYID=1 AND PRIORITY='CRITICAL');

INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY)
SELECT 2, 'HIGH'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_PRIORITY WHERE ISSUE_PRIORITYID=2 AND PRIORITY='HIGH');

INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY)
SELECT 3, 'MEDIUM'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_PRIORITY WHERE ISSUE_PRIORITYID=3 AND PRIORITY='MEDIUM');

INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY)
SELECT 4, 'LOW'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_PRIORITY WHERE ISSUE_PRIORITYID=4 AND PRIORITY='LOW');

INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY)
SELECT 5, 'TRIVIAL'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_PRIORITY WHERE ISSUE_PRIORITYID=5 AND PRIORITY='TRIVIAL');

COMMIT;