INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 1, 'TO_DO'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=1 AND STATUS_NAME='TO_DO');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 2, 'IN_PROGRESS'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=2 AND STATUS_NAME='IN_PROGRESS');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 3, 'CODE_REVIEW'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=3 AND STATUS_NAME='CODE_REVIEW');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 4, 'IN_TESTS'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=4 AND STATUS_NAME='IN_TESTS');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 5, 'DONE'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=5 AND STATUS_NAME='DONE');

INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME)
SELECT 6, 'TEST'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ISSUE_STATUS WHERE STATUSID=6 AND STATUS_NAME='TEST');

COMMIT;