INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (1, 'TO_DO') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (2, 'IN_PROGRESS') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (3, 'CODE_REVIEW') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (4, 'IN_TESTS') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (5, 'DONE') ON CONFLICT DO NOTHING;

INSERT INTO ISSUE_TYPE(ISSUE_TYPEID, TYPE) VALUES (1, 'USER_STORY') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_TYPE(ISSUE_TYPEID, TYPE) VALUES (2, 'BUG') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_TYPE(ISSUE_TYPEID, TYPE) VALUES (3, 'TO_DO') ON CONFLICT DO NOTHING;

INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY) VALUES (1, 'CRITICAL') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY) VALUES (2, 'HIGH') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY) VALUES (3, 'MEDIUM') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY) VALUES (4, 'LOW') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_PRIORITY(ISSUE_PRIORITYID, PRIORITY) VALUES (5, 'TRIVIAL') ON CONFLICT DO NOTHING;

COMMIT;
