INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (1, 'TO_DO') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (2, 'IN_PROGRESS') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (3, 'CODE_REVIEW') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (4, 'IN_TESTS') ON CONFLICT DO NOTHING;
INSERT INTO ISSUE_STATUS(STATUSID, STATUS_NAME) VALUES (5, 'DONE') ON CONFLICT DO NOTHING;

COMMIT;
